  name: Clean GHCR nightly

  on:
    schedule:
      - cron: '0 0 * * *' # Runs daily at midnight UTC.
    workflow_dispatch: # Allows manual triggering.

  jobs:
    cleanup-images:
        name: Clean up trivial images built by ci pipelines for tests.
        runs-on: ubuntu-latest
        steps:
          - uses: snok/container-retention-policy@v3.0.0
            with:
              account: mellonpass
              token: ${{ secrets.CI_PAT }}
              image-names: "web web-cache"
              image-tags: "!main !*.*.*"
              cut-off: 1h  # avoid deleting images used by an active test pipelines.
